from __future__ import annotations

from typing import Any, Protocol


class TraceRecorder(Protocol):
    """AgentLoop/ToolRouter 共同使用的结构化 Trace 最小协议。"""

    run_id: str
    trace_path: Any

    def record_run_start(self, task: str | None = None, metadata: dict | None = None) -> Any: ...
    def record_run_end(self, success: bool, summary: str, metadata: dict | None = None) -> Any: ...
    def record_run_cancelled(self, metadata: dict | None = None) -> Any: ...
    def record_llm_call(self, **kwargs: Any) -> Any: ...
    def record_agent_action(self, **kwargs: Any) -> Any: ...
    def record_agent_observation(self, **kwargs: Any) -> Any: ...
    def record_agent_finish(self, **kwargs: Any) -> Any: ...
    def record_policy_decision(self, **kwargs: Any) -> Any: ...
    def record_permission_request(self, **kwargs: Any) -> Any: ...
    def record_permission_response(self, **kwargs: Any) -> Any: ...
