from __future__ import annotations

"""可选的本地提交准备逻辑。"""

import re
from pathlib import Path

from codepilot.pr_assist.models import CommitPrepError
from codepilot.repo.git_utils import GitCommandError, run_git
from codepilot.repo.protected_paths import DEFAULT_REPO_PROTECTED_PATHS
from codepilot.repo.safety import find_protected_paths, normalize_repo_relative_path


TOKEN_LINE_RE = re.compile(r"(?i)(api[_-]?key|token|secret|password|ghp_|github_pat_|sk-)")


def redact_commit_text(value: str) -> str:
    """把提交信息中疑似敏感行整体替换掉，避免写入 git 历史。"""

    lines: list[str] = []
    for line in value.splitlines():
        if TOKEN_LINE_RE.search(line):
            lines.append("[REDACTED]")
        else:
            lines.append(line.replace("\x00", ""))
    return "\n".join(lines).strip()


def render_commit_message(
    *,
    issue_title: str,
    changed_files: list[str],
    tests_summary: str | None,
    run_id: str,
) -> str:
    """根据 issue 标题和测试摘要生成最小可读提交信息。"""

    title = redact_commit_text(issue_title)[:72] or "CodePilot generated patch"
    lines = [
        f"Fix: {title}",
        "",
        f"Generated by CodePilot Lite from run {run_id}.",
        "",
        "Tests:",
        f"- {redact_commit_text(tests_summary or 'unknown')}",
        "",
        "Changed files:",
    ]
    if changed_files:
        lines.extend(f"- {path}" for path in changed_files)
    else:
        lines.append("- none")
    return "\n".join(lines).rstrip() + "\n"


def get_staged_files(repo_path: str | Path) -> list[str]:
    """读取当前暂存区文件列表，并统一成仓库相对路径格式。"""

    output = run_git(repo_path, ["diff", "--cached", "--name-only"])
    if not output:
        return []
    return [normalize_repo_relative_path(line) for line in output.splitlines() if line.strip()]


def stage_changed_files(repo_path: str | Path, changed_files: list[str]) -> list[str]:
    """只精确暂存 patch metadata 里声明过的 changed_files。"""

    safe_files = [normalize_repo_relative_path(path) for path in changed_files]
    if not safe_files:
        return []
    protected = find_protected_paths(safe_files, DEFAULT_REPO_PROTECTED_PATHS)
    if protected:
        raise CommitPrepError("Refuse to stage protected files: " + ", ".join(protected))
    try:
        run_git(repo_path, ["add", "--", *safe_files], timeout=30)
    except GitCommandError as exc:
        raise CommitPrepError(exc.stderr_summary) from exc
    return get_staged_files(repo_path)


def assert_commit_safety(
    *,
    staged_files: list[str],
    expected_changed_files: list[str],
    run_id: str,
) -> None:
    """在真正 commit 前再次确认暂存区没有越界。"""

    if not staged_files:
        raise CommitPrepError("No staged files to commit.")
    protected = find_protected_paths(staged_files, DEFAULT_REPO_PROTECTED_PATHS)
    if protected:
        raise CommitPrepError("Protected files staged: " + ", ".join(protected))
    run_artifacts = [
        path for path in staged_files if path == "runs" or path.startswith("runs/") or (run_id in path and "runs/" in path)
    ]
    if run_artifacts:
        raise CommitPrepError("Run artifacts must not be committed: " + ", ".join(run_artifacts))
    expected = {normalize_repo_relative_path(path) for path in expected_changed_files}
    unexpected = [path for path in staged_files if path not in expected]
    if unexpected:
        raise CommitPrepError("Unexpected staged files: " + ", ".join(unexpected))


def prepare_commit(
    repo_path: str | Path,
    *,
    message: str,
    changed_files: list[str],
    run_id: str,
    allow_empty: bool = False,
) -> str:
    """只针对声明过的 changed_files 创建一次本地 commit。"""

    staged = stage_changed_files(repo_path, changed_files)
    if not staged and allow_empty:
        try:
            run_git(repo_path, ["commit", "--allow-empty", "-m", redact_commit_text(message)], timeout=30)
        except GitCommandError as exc:
            raise CommitPrepError(exc.stderr_summary) from exc
    else:
        assert_commit_safety(staged_files=staged, expected_changed_files=changed_files, run_id=run_id)
        message_path = Path(repo_path).expanduser().resolve() / ".git" / "CODEPILOT_COMMIT_EDITMSG"
        message_path.write_text(redact_commit_text(message), encoding="utf-8")
        try:
            run_git(repo_path, ["commit", "-F", str(message_path)], timeout=30)
        except GitCommandError as exc:
            raise CommitPrepError(exc.stderr_summary) from exc
        finally:
            try:
                message_path.unlink()
            except FileNotFoundError:
                pass
    return run_git(repo_path, ["rev-parse", "HEAD"])
