from __future__ import annotations

"""生成只放在 runs/<run_id>/ 的 GitHub Action 模板。"""

from pathlib import Path


def render_github_action_template() -> str:
    """输出第十二步只读 dry-run 模板，不写任何真正自动化副作用。"""

    return """name: CodePilot Lite Issue Assist

on:
  workflow_dispatch:
    inputs:
      issue_url:
        description: "GitHub issue URL"
        required: true
      dry_run:
        description: "Generate artifacts only"
        required: true
        default: "true"

permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  codepilot-issue-assist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install CodePilot Lite
        run: |
          python -m pip install -e .
      - name: Run CodePilot Lite in dry-run mode
        run: |
          echo "This template is generated by CodePilot Lite Manual PR Assist."
          echo "Keep dry_run=true and read-only permissions for this stage."
          python -m codepilot.cli issue "${{ inputs.issue_url }}" --repo . --dirty-policy fail --manifest --restore-plan

# Step 13 may introduce write permissions, branch push, PR creation, and issue comments.
# Do not enable write permissions in Step 12.
"""


def write_github_action_template(output_path: str | Path, *, overwrite: bool = False) -> Path:
    """只把模板写入 run artifact，不写入 .github/workflows。"""

    path = Path(output_path)
    if path.exists() and not overwrite:
        raise FileExistsError(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_github_action_template(), encoding="utf-8")
    return path
